ROWS = 8
COLS = 8

### Tile types ###
EMPTY_TILE = 0
WHITE_COLOR = 1
BLACK_COLOR = 2
QUEEN = 4
WHITE_PIECE = WHITE_COLOR
BLACK_PIECE = BLACK_COLOR
WHITE_QUEEN = WHITE_COLOR | QUEEN
BLACK_QUEEN = BLACK_COLOR | QUEEN

### Dimensions ###
# Screen dimensions:
BOARD_OUTLINE_SIZE = 20
TILE_SIZE = 75
SCREEN_WIDTH = 2 * BOARD_OUTLINE_SIZE + COLS * TILE_SIZE
SCREEN_HEIGHT = 2 * BOARD_OUTLINE_SIZE + ROWS * TILE_SIZE
PLAYED_TILE_OUTLINE_SIZE = 3

# Menu dimensions:
BUTTON_WIDTH = SCREEN_WIDTH // 3
BUTTON_HEIGHT = SCREEN_HEIGHT // 8

# Piece dimensions:
SHADOW_SIZE = 6

### Borders ###
TOP_BORDER = 0
BOTTOM_BORDER = ROWS - 1
LEFT_BORDER = 0
RIGHT_BORDER = COLS - 1

### Colors ###
# Tile colors:
WHITE_TILE_COLOR = (235, 229, 224)
BLACK_TILE_COLOR = (154, 127, 101)
SELECTED_TILE_BLACK_COLOR = (0, 100, 100)
SELECTED_TILE_WHITE_COLOR = (139, 0, 0)
UNDO_SELECTED_TILE_COLOR = (0, 0, 0)
BOARD_OUTLINE_COLOR = (100, 83, 67)
SELECTED_TILE_BASE_COLOR = (80, 63, 47)

# Piece colors:
WHITE_PIECE_COLOR = (220, 0, 0)
WHITE_PIECE_SHADOW_COLOR = (136, 7, 7)
BLACK_PIECE_COLOR = (0, 100, 200)
BLACK_PIECE_SHADOW_COLOR = (14, 68, 139)

# Menu colors:
BUTTON_COLOR = BLACK_TILE_COLOR
MAIN_MENU_COLOR = (235, 229, 224)
ACTIVE_BUTTON_COLOR = (60, 43, 27)
TEXT_COLOR = WHITE_TILE_COLOR
HEADER_COLOR = BLACK_TILE_COLOR

### Fonts ###
TEXT_SIZE = 30
HEADER_SIZE = 72
