EMPTY_TILE = 0
WHITE_COLOR = 1
BLACK_COLOR = 2
QUEEN = 4

WHITE_PIECE = WHITE_COLOR
BLACK_PIECE = BLACK_COLOR
WHITE_QUEEN = WHITE_COLOR | QUEEN
BLACK_QUEEN = BLACK_COLOR | QUEEN

ROWS = 8
COLS = 8
TILE_SIZE = 65

TOP_BORDER = 0
BOTTOM_BORDER = ROWS - 1
LEFT_BORDER = 0
RIGHT_BORDER = COLS - 1

WHITE_TILE_COLOR = (235, 229, 224)
BLACK_TILE_COLOR = (154, 127, 101)

WHITE_PIECE_COLOR = (220, 0, 0)
WHITE_PIECE_SHADOW_COLOR = (136, 7, 7)
BLACK_PIECE_COLOR = (0, 100, 200)
BLACK_PIECE_SHADOW_COLOR = (14, 68, 139)

VALID_MOVE_COLOR = (0, 255, 0)

BOARD_OUTLINE_SIZE = 20
BOARD_OUTLINE_COLOR = (93, 76, 60)
SCREEN_WIDTH = 2 * BOARD_OUTLINE_SIZE + COLS * TILE_SIZE
SCREEN_HEIGHT = 2 * BOARD_OUTLINE_SIZE + ROWS * TILE_SIZE
SHADOW_SIZE = 6

MAIN_MENU_COLOR = (235, 229, 224)

BUTTON_COLOR = BLACK_TILE_COLOR
BUTTON_WIDTH = SCREEN_WIDTH // 3
BUTTON_HEIGHT = SCREEN_HEIGHT // 8
ACTIVE_BUTTON_COLOR = (0, 0, 0)
TEXT_COLOR = WHITE_TILE_COLOR
HEADER_COLOR = BLACK_TILE_COLOR
